# Project information
site_name: Gluu Docs
site_description: Documentation for Gluu Server Community Edition
site_favicon: 'favicon.ico'

# Copyright
copyright: Copyright &copy; 2019, Gluu, Inc.

# Repository
docs_dir: source
#repo_name: GluuFederation/docs-ce-prod
repo_url: https://github.com/GluuFederation/docs-ce-prod/tree/2.4.4/2.4.4
#repo_url: https://github.com/GluuFederation/docs-ce-prod/
#edit_uri: edit/2.4.4/docs/source

# Configuration
theme_dir: theme/material
#theme: 
#    name: material
#    palette:
#        primary: 'green'
#        accent: 'green'
#    logo: 'gluu.jpg'
#    favicon: 'favicon.ico'
extra:
    version: '2.4.4'
    logo: 'gluu.png'
    
# Extensions
markdown_extensions:
- admonition
- toc:
     permalink: '#'
#- codehilite     
- pymdownx.superfences

# Navigation
#nav:
#- 'Versions':
#    - '2.4.4': 'https://gluu.org/docs/ce/2.4.4/'
#    - '3.1.6': 'https://gluu.org/docs/ce/3.1.6/'
#    - '3.1.5': 'https://gluu.org/docs/ce/3.1.5/'
#    - '3.1.4': 'https://gluu.org/docs/ce/3.1.4/'
#    - '3.1.3.1': 'https://gluu.org/docs/ce/3.1.3.1/'
#    - '3.1.3': 'https://gluu.org/docs/ce/3.1.3/'
#    - '3.1.2': 'https://gluu.org/docs/ce/3.1.2/'
#    - '3.1.1': 'https://gluu.org/docs/ce/3.1.1/'
#    - '3.1.0': 'https://gluu.org/docs/ce/3.1.0/'
#    - '3.0.2': 'https://gluu.org/docs/ce/3.0.2/'
#    - '3.0.1': 'https://gluu.org/docs/ce/3.0.1/'
pages:
- Home: 'index.md'
- Gluu Introduction:
        - 'History': 'introduction/history.md'
        - 'Design Goals': 'introduction/design.md'
        - 'Gluu Server Architecture': 'introduction/architecture.md'
#- Whats new in 3.0: 'operation/intro.md'
- Installation Guide:
        - 'Preparing VM': 'installation-guide/index.md'
        - 'Install Gluu Server': 'installation-guide/install.md'
#        - 'Cluster with CE': 'installation-guide/cluster.md'
        - 'Setup Script Options': 'installation-guide/setup_py.md'
        - Upgrade/Patch Guide:
            - 'Upgrade Gluu Server' : 'upgrade/upgrading.md'
#          - 'Patch Gluu Server' : 'upgrade/update.md'
            - 'Updating Gluu Server': 'upgrade/updating.md'
        -  Cluster Configuration:
            - 'Requirements: csync2 Installation': 'cluster/csync-installation.md'
            - 'Clustering with CE': 'cluster/index.md'
- Administration Guide:
        - 'oxTrust admin UI' : 'admin-guide/oxtrust-ui.md'
        - 'Interception Scripts': 'admin-guide/custom-script.md'
        - User Authentication Guide:
            - 'User Authentication Introduction': 'admin-guide/user-authentications.md'
            - 'Social Authentication': 'authn-guide/passport.md'
            - 'Super Gluu': 'authn-guide/supergluu.md'
            - 'FIDO U2F': 'authn-guide/U2F.md'
            - 'Duo Security': 'authn-guide/duo.md'
            - 'Certificate Authentication': 'authn-guide/cert-auth.md'
            - 'Google': 'authn-guide/google.md'
            - 'HOTP/TOTP': 'authn-guide/otp.md'
            - 'Custom Authentication': 'authn-guide/customauthn.md'
            - 'Custom Attributes': 'admin-guide/attributes.md'
        - 'User Management' : 'admin-guide/user-management.md'
        - 'Session timeout Configuration': 'admin-guide/config.md'
#       - 'SSO Protocols' : 'admin-guide/auth-protocol.md'
#       - 'Gluu for Mobile' : 'admin-guide/mobile.md'
#       - 'Self-Services for Users' : 'admin-guide/self-service.md'
        - 'SAML' : 'admin-guide/saml.md'
        - 'OAuth2 Grants' : 'admin-guide/oauth2.md'
        - 'OpenID Connect' : 'admin-guide/openid-connect.md'
        - 'UMA' : 'admin-guide/uma.md'
        - 'SCIM protected by UMA' : 'admin-guide/scim-uma.md'
        - 'Certificate Management' : 'admin-guide/certificates.md'
- Integration Guide:
#    - 'Integration in Gluu Server': 'integration/index.md'
        - 'Developer Guide':
            - 'oxd OAuth2': 'integration/oauth2.md'
            - 'OAuth2.0 js Implicit Flow': 'integration/oauth-js-implicit.md'
        - 'Web Server Integrations':
            - 'Shibboleth SP': 'integration/saml-sp.md'
            - 'mod_auth_openidc': 'integration/openidc-rp.md'
        - 'SaaS Integrations':
            - 'Google SSO': 'integration/google.md'
            - 'Office 365': 'integration/office.md'
            - 'Hobsons Education Sol': 'integration/hobsons.md'
            - 'Salesforce': 'integration/salesforce.md'
            - 'Dropbox': 'integration/dropbox.md'
- Reference:
        - Gluu API Guide:
            - 'Custom ID Generation': 'api-guide/api.md'
            - 'OpenID Connect API': 'api-guide/openid-connect-api.md'
            - 'SCIM API Configuration': 'api-guide/scim-api.md'
            - 'UMA API': 'api-guide/uma-api.md'
        - 'JSON Properties':
            - 'OxTrust JSON Properties': 'reference/JSON-oxtrust-prop.md'
            - 'OxAuth JSON Properties': 'reference/JSON-oxauth-prop.md'
        #- 'Ox LDAP Properties':
        - 'Gluu LDAP Schema':
            - 'OpenLDAP Schema': 'reference/schema.md'
- Operation Guide:
        - 'Patches': 'upgrade/patches.md'
        - 'Backups': 'operation/backup.md'
        - 'Find your Gluu Version': 'operation/find-gluu-server-version.md'
        - 'Ports': 'operation/ports.md'
        - 'Single Logout (SLO)': 'operation/logout.md'
        - 'Log Management' : 'operation/logs.md'
        - 'Customize Gluu Login Page': 'operation/design.md'
        - 'FAQ & Troubleshooting' : 'operation/faq.md'
        - 'Tuning LDAP, Tomcat': 'operation/fine-tuning.md'
        - 'Update Certificate': 'operation/update-certificate.md'
