site_name: Gluu Docs
site_description: Documenation for Gluu Server
site_favicon: 'favicon.ico'
copyright: Copyright &copy; 2017, Gluu, Inc.
docs_dir: source
repo_url: https://github.com/GluuFederation/docs-ce-prod/tree/3.1.1/3.1.1
theme_dir: theme/material
extra:
    version: '3.1.1'
    logo: 'gluu.png'
markdown_extensions:
- admonition
- toc:
     permalink: '#'
pages:
- Home: 'index.md'
- Release Notes: 'release-notes/index.md'
- Whats new in 3.x: '3.x-intro.md'
- Whats new in 3.1.x: '3.1.x-intro.md'
- Installation Guide:
        - 'Preparing VM': 'installation-guide/index.md'
        - 'Install Gluu Server': 'installation-guide/install.md'
        - 'Setup Script Options': 'installation-guide/setup_py.md'
        - 'Clustering': 'installation-guide/cluster.md'
        - Upgrade/Patch Guide:
          - 'Upgrade Gluu Server' : 'upgrade/index.md'
          - 'Upgrade Gluu Server with OpenDJ': 'upgrade/manual-update.md'
        #- 'Patch Gluu Server' : 'upgrade/update.md'
          - 'Updating a War File': 'upgrade/update-war.md'
        - 'Containership.io Installation': 'installation-guide/containership.md'
- Administration Guide:
        - 'oxTrust admin UI' : 'admin-guide/oxtrust-ui.md'
        - 'Interception Scripts': 'admin-guide/custom-script.md'
        - User Management:
            - 'Local User Management': 'user-management/local-user-management.md'
            - 'AD/LDAP Synchronization': 'user-management/ldap-sync.md'
            - 'SCIM 2.0 User Management': 'user-management/scim2.md'
        - User Authentication:
            - 'Introduction': 'authn-guide/intro.md'
            - 'Basic Authentication': 'authn-guide/basic.md'
            - 'Inbound SAML': 'authn-guide/inbound-saml-passport.md'
            - 'Social Login using Passport.js': 'authn-guide/passport.md'
            - 'FIDO U2F': 'authn-guide/U2F.md'
            - 'Super Gluu': 'authn-guide/supergluu.md'
            - 'Duo Security': 'authn-guide/duo.md'
            - 'HOTP/TOTP': 'authn-guide/otp.md'
            - 'SMS OTP': 'authn-guide/sms-otp.md'
            - 'Certificate Authentication': 'authn-guide/cert-auth.md'
            - 'Google+ OAuth 2.0': 'authn-guide/google.md'
            - 'Account Lockout': 'authn-guide/lockout.md'
            - 'Custom Script Tutorial': 'authn-guide/customauthn.md'
            #- 'Inbound SAML using Asimba' : 'authn-guide/inbound-saml-asimba.md'
        - 'Attributes' : 'admin-guide/attribute.md'
        #- 'SCIM protected by UMA' : 'admin-guide/scim-uma.md'
        - 'SAML IDP' : 'admin-guide/saml.md'
        #        - 'OAuth2 Grants' : 'admin-guide/oauth2.md'
        - 'OpenID Connect Provider (OP)' : 'admin-guide/openid-connect.md'
        - 'UMA Authorization Server (AS)' : 'admin-guide/uma.md'
        - 'Central Authentication Service (CAS)' : 'admin-guide/cas.md'
        - 'Session Management': 'admin-guide/session.md'
        - 'Certificate Management' : 'admin-guide/certificate.md'
        - 'CORS Configuration' : 'admin-guide/cors.md'
- SSO Integration Guide:
        - 'Introduction': 'integration/index.md'
        - 'Server Side Web Apps':
            - 'oxd OAuth 2.0': 'integration/oxd-oauth2/index.md'
            - 'Nginx lua-resty-openidc': 'integration/sswebapps/nginx.md'
            - 'Apache mod_auth_openidc': 'integration/sswebapps/openidc-rp.md'
            - 'Shibboleth SAML SP': 'integration/sswebapps/saml-sp.md'
        - 'Single Page Apps':
            - 'AppAuth JS': 'integration/spa/appauth-js.md'
            - 'Gluu OIDC JS Client': 'integration/spa/oauth-js-implicit.md'
        - 'Native Apps':
            - 'AppAuth iOS and macOS': 'integration/native-apps/appauth-ios.md'
            - 'AppAuth Android': 'integration/native-apps/appauth-android.md'
        - 'SaaS Integrations':
            - 'Google Apps': 'integration/saas/google.md'
            - 'Office 365': 'integration/saas/office.md'
            - 'Testing Shibboleth with TestShib2': 'integration/saas/testShib2.md'
#    - 'Hobsons Education Sol': 'integration/saas/hobsons.md'
            - 'Salesforce': 'integration/saas/salesforce.md'
            - 'Dropbox': 'integration/saas/dropbox.md'
            - 'GitHub Enterprise': 'integration/saas/github-enterprise.md'
            - 'Cisco WebEx': 'integration/saas/webex.md'
            - 'Amazon Web Services (AWS)': 'integration/saas/aws.md'
- Reference:
        - Gluu API Guide:
            - 'Custom ID Generation': 'api-guide/api.md'
            - 'OpenID Connect API': 'api-guide/openid-connect-api.md'
            - 'SCIM API Configuration': 'api-guide/scim-api.md'
            - 'UMA API': 'api-guide/uma-api.md'
        - 'JSON Properties':
            - 'oxTrust JSON Properties': 'reference/JSON-oxtrust-prop.md'
            - 'oxAuth JSON Properties': 'reference/JSON-oxauth-prop.md'
        - 'Gluu LDAP Schema':
            - 'oxLDAP Properties': 'reference/oxldap.md'
            - 'OpenLDAP Schema': 'reference/schema.md'
- Operation Guide:
        - 'Patches': 'upgrade/patches.md'
        - 'Backups': 'operation/backup.md'
        - 'Find your Gluu Version': 'operation/find-gluu-version.md'
        - 'Ports': 'operation/ports.md'
        - 'Logout': 'operation/logout.md'
        - 'Log Management' : 'operation/logs.md'
        - 'Customize Public Pages': 'operation/custom-design.md'
        - 'FAQ & Troubleshooting': 'operation/faq.md'
        - 'Change IP Address': 'operation/changeip.md'
        #       - 'Fine Tuning Gluu Server' : 'admin-guide/fine-tuning.md'
- Developer Guide:
        - 'Build oxTrust with Eclipse': 'developer-guide/oxtrust-eclipse.md'
        - 'Localization': 'developer-guide/localization.md'
