# Project information
site_name: Gluu Server 4.2 Docs
site_description: Documentation for Gluu Server Community Edition

# Copyright
copyright: Copyright &copy; 2019, Gluu, Inc.

# Repository
docs_dir: source
repo_name: GluuFederation/docs-ce-prod
repo_url: https://github.com/GluuFederation/docs-ce-prod/
edit_uri: edit/4.2/docs/source

# Configuration
theme: 
    name: material
    custom_dir: 'theme'
    palette:
        primary: 'green'
        accent: 'green'
    logo: 'gluu.jpg'
    favicon: 'favicon.ico'
extra:
    version: '4.2'
    
# Extensions
markdown_extensions:
- admonition
- toc:
     permalink: '#'
- codehilite     
- pymdownx.superfences

# Navigation
nav:
- 'Versions':
    - '4.2': 'https://gluu.org/docs/ce/4.2/'
    - '4.1': 'https://gluu.org/docs/ce/4.1/'
    - '4.0': 'https://gluu.org/docs/ce/4.0/'
    - '3.1.6': 'https://gluu.org/docs/ce/3.1.6/'
    - '3.1.5': 'https://gluu.org/docs/ce/3.1.5/'
    - '3.1.4': 'https://gluu.org/docs/ce/3.1.4/'
    - '3.1.3.1': 'https://gluu.org/docs/ce/3.1.3.1/'
    - '3.1.3': 'https://gluu.org/docs/ce/3.1.3/'
    - '3.1.2': 'https://gluu.org/docs/ce/3.1.2/'
    - '3.1.1': 'https://gluu.org/docs/ce/3.1.1/'
    - '3.1.0': 'https://gluu.org/docs/ce/3.1.0/'
    - '3.0.2': 'https://gluu.org/docs/ce/3.0.2/'
    - '3.0.1': 'https://gluu.org/docs/ce/3.0.1/'
    - '2.4.4': 'https://gluu.org/docs/ce/2.4.4/'
- ' ': 'https://gluu.org/docs'
- ' ': 'https://gluu.org/docs'
- Home: 'index.md'
- Release Notes: 'release-notes/index.md'
- Whats new in v4: '4.x-intro.md'
- Installation Guide:
        - 'VM Preparation': 'installation-guide/index.md'
        - 'Installation': 
#            - 'Start here': 'installation-guide/install.md'
            - 'Test Drive': 'installation-guide/test-drive.md'
            - 'Docker': 'installation-guide/install-docker.md'
            - 'Ubuntu': 'installation-guide/install-ubuntu.md'
            - 'Debian': 'installation-guide/install-debian.md'
            - 'RHEL': 'installation-guide/install-rhel.md'
            - 'CentOS': 'installation-guide/install-centos.md'
        - 'Setup Script Options': 'installation-guide/setup_py.md'
        - 'Clustering': 'installation-guide/cluster.md'
- Administration Guide:
        - 'oxTrust admin UI': 'admin-guide/oxtrust-ui.md'
        - 'Interception Scripts': 'admin-guide/custom-script.md'
        - User Management:
            - 'Local User Management': 'user-management/local-user-management.md'
            - 'AD/LDAP Synchronization': 'user-management/ldap-sync.md'
            - 'IDM Synchronization': 'user-management/idm-sync.md'
            - 'User Registration': 'user-management/user-registration.md'
            - 'SCIM 2.0 User Management': 'user-management/scim2.md'
        - User Authentication:
            - 'Introduction': 'authn-guide/intro.md'
            - 'Basic Authentication': 'authn-guide/basic.md'
            - 'FIDO U2F': 'authn-guide/U2F.md'
            - 'FIDO 2.0': 'authn-guide/fido2.md'
            - 'Super Gluu': 'authn-guide/supergluu.md'
            - 'OTP apps': 'authn-guide/otp.md'
            - 'SMS OTP (Twilio)': 'authn-guide/sms-otp.md'
            - 'SMS OTP (SMPP)': 'authn-guide/sms-otp-smpp.md'
            - 'Duo Security': 'authn-guide/duo.md'
            - 'ThumbSignIn': 'authn-guide/thumbsignin.md'
            - 'Certificate Authentication': 'authn-guide/cert-auth.md'
            - 'Account Lockout': 'authn-guide/lockout.md'
            - 'Forgot Password': 'authn-guide/pw-reset.md'
            - 'Custom Script Tutorial': 'authn-guide/customauthn.md'
        - Inbound Identity:
            - 'Introduction': 'authn-guide/passport.md'
            - 'Inbound OAuth & OpenID Connect': 'authn-guide/inbound-oauth-passport.md'
            - 'Inbound SAML': 'authn-guide/inbound-saml-passport.md'
        - 'RADIUS':
            - 'Gluu Radius': 'admin-guide/radius-server/gluu-radius.md'
            - 'Radiator Plugin': 'admin-guide/radius-server/gluu-radiator.md'
        - 'Attributes': 'admin-guide/attribute.md'
        - 'SAML IDP': 'admin-guide/saml.md'
        - 'OpenID Connect Provider (OP)': 'admin-guide/openid-connect.md'
        - 'UMA Authorization Server (AS)': 'admin-guide/uma.md'
        - 'Central Authentication Service (CAS)': 'admin-guide/cas.md'
        - 'Session Management': 'admin-guide/session.md'
        - 'Certificate Management': 'admin-guide/certificate.md'
        - 'CORS Configuration': 'admin-guide/cors.md'
- Integration Guide:
        - 'Introduction': 'integration/index.md'
        - 'Server Side Web Apps':
            - 'OAuth2 Grants': 'admin-guide/oauth2.md'
            - 'oxd OAuth 2.0': 'integration/oxd-oauth2/index.md'
            - 'Nginx lua-resty-openidc': 'integration/sswebapps/nginx.md'
            - 'Apache mod_auth_openidc': 'integration/sswebapps/openidc-rp.md'
            - 'Shibboleth SAML SP': 'integration/sswebapps/saml-sp.md'
        - 'Single Page Apps':
            - 'AppAuth JS': 'integration/spa/appauth-js.md'
            - 'Gluu OIDC JS Client': 'integration/spa/oauth-js-implicit.md'
        - 'Native Apps':
            - 'AppAuth iOS and macOS': 'integration/native-apps/appauth-ios.md'
            - 'AppAuth Android': 'integration/native-apps/appauth-android.md'
        - 'SaaS / Off-the-shelf Apps':
            - 'Google Apps': 'integration/saas/google.md'
            - 'Office 365': 'integration/saas/office.md'
            - 'Moodle': 'integration/saas/moodle.md'
            - 'Salesforce': 'integration/saas/salesforce.md'
            - 'Dropbox': 'integration/saas/dropbox.md'
            - 'GitHub Enterprise': 'integration/saas/github-enterprise.md'
            - 'Cisco WebEx': 'integration/saas/webex.md'
            - 'Amazon Web Services (AWS)': 'integration/saas/aws.md'
            - 'Rocketchat': 'integration/saas/rocketchat.md'
            - 'SAMLtest.id': 'integration/saas/saml_test_id.md'
- Reference:
        - Gluu API Guide:
            - 'Gluu Server API': 'api-guide/api.md'
            - 'OpenID Connect API': 'api-guide/openid-connect-api.md'
            - 'SCIM API': 'api-guide/scim-api.md'
            - 'UMA API': 'api-guide/uma-api.md'
        - 'JSON Properties':
            - 'oxTrust JSON Properties': 'reference/JSON-oxtrust-prop.md'
            - 'oxAuth JSON Properties': 'reference/JSON-oxauth-prop.md'
            - 'Cache Provider Configuration': 'reference/cache-provider-prop.md'
        - 'Persistence Strategies':
            - 'Persistence Mechanisms': 'reference/persistence.md'
            - 'oxLDAP Properties': 'reference/oxldap.md'
            - 'LDAP Schema': 'reference/schema.md'
- Operation Guide:
        - 'Service Commands': 'operation/services.md'
        - 'Upgrades': 'upgrade/index.md'
        - 'Patches': 'upgrade/patches.md'
        - 'Backups': 'operation/backup.md'
        - 'Security tips': 'operation/security.md'
        - 'Performance tuning': 'operation/fine-tuning.md'
        - 'Ports': 'operation/ports.md'
        - 'Logout': 'operation/logout.md'
        - 'Log Management' : 'operation/logs.md'
        - 'Customize Public Pages': 'operation/custom-design.md'
        - 'Change IP Address': 'operation/changeip.md'
        - 'Server Clean-up': 'operation/cleanup.md'
        - 'Replacing Expired JKS Files': 'operation/replace-expired-jks-scim.md'
- Developer Guide:
#        - 'Build oxTrust with Eclipse': 'developer-guide/oxtrust-eclipse.md'
        - 'Localization': 'developer-guide/localization.md'
        - 'Script Debugging': 'developer-guide/script-debugging.md'
- Tutorials:
        - 'Attributes mapping and transformation in Passport': 'tutorials/passport-attributes-mapping.md'
        - 'Inbound Identity with Apple Sign In': 'tutorials/passport-apple.md'
        - 'Inbound SAML with Passport': 'tutorials/passport-inbound-flow.md'
        - 'Forgot PW': 'tutorials/forgot-pw.md'
        - 'Kafka Logging': 'tutorials/kafka.md'
- FAQ & Troubleshooting: 'operation/faq.md'
